String gauge_str = "<script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>"
"<script type=\"text/javascript\">"
"google.charts.load('current', {'packages':['gauge']});"
"google.charts.setOnLoadCallback(drawChart);"
"function drawChart() {"
""
"var data = google.visualization.arrayToDataTable(["
"['Label', 'Value'],"
"['|NAME1|', |VAL1|],"
"['|NAME2|', |VAL2|]"
"]);"
""
"var options = {"
"width: 400, height: 120,"
"max:100,"
"minorTicks: 5"
"};"
""
"var chart = new google.visualization.Gauge(document.getElementById('c_div'));"
""
"chart.draw(data, options);"
""
"}"
"</script>"
"<div id=\"c_div\" style=\"width: 400px; height: 120px;\"></div>";
